# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\dialogexpense.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(386, 330)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.comboBoxCategory = QtWidgets.QComboBox(Dialog)
        self.comboBoxCategory.setObjectName("comboBoxCategory")
        self.gridLayout.addWidget(self.comboBoxCategory, 1, 1, 1, 1)
        self.doubleSpinBoxAmount = QtWidgets.QDoubleSpinBox(Dialog)
        self.doubleSpinBoxAmount.setMaximum(99999999999.0)
        self.doubleSpinBoxAmount.setSingleStep(0.05)
        self.doubleSpinBoxAmount.setObjectName("doubleSpinBoxAmount")
        self.gridLayout.addWidget(self.doubleSpinBoxAmount, 2, 1, 1, 1)
        self.lineEditCue = QtWidgets.QLineEdit(Dialog)
        self.lineEditCue.setObjectName("lineEditCue")
        self.gridLayout.addWidget(self.lineEditCue, 3, 1, 1, 1)
        self.lineEditRemark = QtWidgets.QLineEdit(Dialog)
        self.lineEditRemark.setObjectName("lineEditRemark")
        self.gridLayout.addWidget(self.lineEditRemark, 4, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Betrag"))
        self.label.setText(_translate("Dialog", "Datum"))
        self.label_2.setText(_translate("Dialog", "Kategorie"))
        self.label_4.setText(_translate("Dialog", "Stichwort"))
        self.label_5.setText(_translate("Dialog", "Bemerkung"))
        self.comboBoxCategory.setPlaceholderText(_translate("Dialog", "---"))
